/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const derive_public_key_hex: (a: number, b: number) => [number, number, number, number];
export const __wbg_wasmscanner_free: (a: number, b: number) => void;
export const create_wasm_scanner: (a: number, b: number) => [number, number, number];
export const initialize_http_scanner: (a: number, b: number, c: number) => any;
export const process_http_blocks_async: (a: number, b: number, c: number, d: number, e: number) => any;
export const process_http_blocks: (a: number, b: number, c: number) => [number, number, number, number];
export const scan_block_data: (a: number, b: number, c: number) => [number, number, number, number];
export const scan_single_block: (a: number, b: number, c: number) => [number, number, number, number];
export const get_scanner_stats: (a: number) => [number, number, number, number];
export const get_scanner_state: (a: number) => [number, number];
export const reset_scanner: (a: number) => void;
export const cleanup_scanner_transactions: (a: number, b: number) => void;
export const get_tip_info: (a: number) => any;
export const fetch_blocks_by_heights: (a: number, b: number, c: number) => any;
export const search_utxos: (a: number, b: number, c: number) => any;
export const create_scan_config: (a: number, b: bigint, c: number, d: bigint) => [number, number, number, number];
export const get_version: () => [number, number];
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_export_4: WebAssembly.Table;
export const __wbindgen_export_5: WebAssembly.Table;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const closure114_externref_shim: (a: number, b: number, c: any) => void;
export const closure160_externref_shim: (a: number, b: number, c: any, d: any) => void;
export const __wbindgen_start: () => void;
